services:
  proxy:
    image: traefik:v3.0
    container_name: proxy
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=true
      - --log.level=INFO
      - --accesslog=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy
      - --entrypoints.web.address=:80
    restart: always
    ports:
      - ${TRAEFIK_HOST_PORT80:-80}:80
      - ${TRAEFIK_HOST_PORT8080:-8080}:8080
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.proxy.rule=Host(`${PROXY_PATH:-proxy}.${PATH_SUFFIX:-localhost}`)
      - traefik.http.routers.proxy.entrypoints=web
      - traefik.http.routers.proxy.service=proxy
      - traefik.http.services.proxy.loadbalancer.server.port=8080

  app:
    image: hhh/app
    container_name: app
    build: ./app
    restart: on-failure:3
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--no-warnings
    user: node
    ports:
      - ${APP_HOST_PORT:-3000}:3000
    networks:
      - proxy
    depends_on:
      - fuseki
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`${APP_PATH:-app}.${PATH_SUFFIX:-localhost}`)
      - traefik.http.routers.app.entrypoints=web
      - traefik.http.routers.app.service=app
      - traefik.http.services.app.loadbalancer.server.port=3000
    develop:
      watch:
        - path: ./app
          action: rebuild

  fuseki:
    image: hhh/fuseki
    container_name: fuseki
    build: ./fuseki
    restart: always
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    ports:
      - ${FUSEKI_HOST_PORT:-3030}:3030
    networks:
      - proxy
    volumes:
      - fuseki-data:/fuseki
    depends_on:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.fuseki.rule=Host(`${FUSEKI_PATH:-fuseki}.${PATH_SUFFIX:-localhost}`)
      - traefik.http.routers.fuseki.entrypoints=web
      - traefik.http.routers.fuseki.service=fuseki
      - traefik.http.services.fuseki.loadbalancer.server.port=3030

  translate:
    image: libretranslate/libretranslate
    container_name: translate
    restart: always
    ports:
      - 5001:5000
    volumes:
      - translate-data:/root/.local/share/argos-translate/packages
    networks:
      - proxy
    environment:
      - LT_HOST=0.0.0.0
      - LT_DEBUG=true
      - LT_REQ_LIMIT=0
    tty: true
    depends_on:
      - app
    labels:
      - traefik.enable=true
      - traefik.http.routers.translate.rule=Host(`${TRANSLATE_PATH:-translate}.${PATH_SUFFIX:-localhost}`)
      - traefik.http.routers.translate.entrypoints=web
      - traefik.http.routers.translate.service=translate
      - traefik.http.services.translate.loadbalancer.server.port=5000

networks:
  proxy:
    name: proxy

volumes:
  fuseki-data:
    name: fuseki-data
  translate-data:
    name: translate-data
