version: "3.8"

services:
  redis:
    image: redis:7-alpine

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - src/openapi_server/.env
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
    command: uvicorn src.openapi_server.main:app --host 0.0.0.0 --port 8080 --reload

