# coding: utf-8

"""
    API Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI
import uvicorn
from pathlib import Path
import os
from dotenv import load_dotenv
BASE_DIR = Path(__file__).resolve().parent
load_dotenv(BASE_DIR / ".env")
from openapi_server.apis.classify_context_api import router as ClassifyContextApiRouter
from openapi_server.apis.classify_habit_api import router as ClassifyHabitApiRouter
from openapi_server.apis.system_api import router as SystemApiRouter

app = FastAPI(
    title="Habit Classifier",
    description="A habit classification system leveraging an LLM to decide if a sentence constitutes a habit and to extract its contextual information. Data is cached in Redis, with results persisted to MongoDB",
    version="0.1.0",
)

app.include_router(ClassifyContextApiRouter)
app.include_router(ClassifyHabitApiRouter)
app.include_router(SystemApiRouter)

